timeout: 3
# interface_resolution: 1024x768x32

/Linux: tiny kernel 6.19
    protocol:       linux
    path:           boot():/bzImage
    module_path:    boot():/initrd
    resolution:     1024x768x32
    textmode:       yes
    #kernel_cmdline: initrd=initrd
